image_to_gridmap:
  ros__parameters:
    image_topic: "/image_raw"
    resolution: 0.5
    map_frame_id: "map"
    min_height: -5.0
    max_height: 0.0

grid_map_visualization:
  ros__parameters:
    grid_map_topic: /filtered_map
    grid_map_visualizations: [surface_normals, traversability_grid] 
    surface_normals:
      type: vectors
      params:
        layer_prefix: normal_vectors_
        position_layer: elevation
        scale: 0.06
        line_width: 0.005
        color: 15600153 # red
    traversability_grid:
      type: occupancy_grid
      params:
        layer: obstacle_a
        data_min: 0.0
        data_max: 5.0


