image_to_gridmap:
  ros__parameters:
    image_topic: "/image_raw"
    resolution: 0.5
    map_frame_id: "map"
    min_height: -5.0
    max_height: 0.0
    output_topic: /filtered_map
    filters:
      # filter1:
      #   name: buffer_normalizer
      #   type: gridMapFilters/BufferNormalizerFilter

      # filter2: # Duplicate layer.
      #   name: inverter
      #   type: gridMapFilters/MathExpressionFilter
      #   params:
      #     output_layer: elevation
      #     expression: -elevation
      #     # expression: abs(elevation - elevation_smooth) # Surface roughness.
      #     # expression: 0.5 * (1.0 - (slope / 0.6)) + 0.5 * (1.0 - (roughness / 0.1)) # Weighted and normalized sum.
      
      # filter3: # Duplicate layer.
      #   name: obstacle_dup
      #   type: gridMapFilters/DuplicationFilter
      #   params:
      #     input_layer: elevation
      #     output_layer: obstacle_a


      filter1: # Duplicate layer.
        name: obstacle_a
        type: gridMapFilters/MultiObstacleFilter
        params:
          layer: elevation
          obstacles:
            # "x,     y,    l,    w,   r,   h,   s_d,  f, fv, type, b"
            - "-5.5, -15.5, 20.2, 5.3, 2.5, 5.0, 3.10, 2, 000, 0, 0.5" 
            # - "30.5, -30.5, 20.2, 5.3, 2.5, 5.0, 3.20, 0, 000, 1, 0.5"
            # - "30.5, -45.5, 20.2, 5.3, 2.5, 5.0, 3.30, 2, 000, 0, 0.5"
            # - "30.5, -60.5, 20.2, 5.3, 2.5, 5.0, 3.30, 3, 150, 0, 0.5"
          output_layer: obstacle_a


grid_map_visualization:
  ros__parameters:
    grid_map_topic: /filtered_map
    grid_map_visualizations: [surface_normals, traversability_grid] 
    surface_normals:
      type: vectors
      params:
        layer_prefix: normal_vectors_
        position_layer: elevation
        scale: 0.06
        line_width: 0.005
        color: 15600153 # red
    traversability_grid:
      type: occupancy_grid
      params:
        layer: obstacle_a
        data_min: 0.0
        data_max: 5.0


